# Generated by Django 5.2 on 2025-06-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'created')), fields=('artwork',), name='unique_artwork_in_cart'),
        ),
    ]
